### PR TITLE
tomcat 8.5

### LINKED ISSUE #41: Migrate tomcat:jre8 (Tomcat 8.5)
eventually... Migration guide is [here](https://tomcat.apache.org/migration-85.html#Migrating_from_8.0.x_to_8.5.x).

[Also Tomcat 8.0 will be EOLed soon](https://tomcat.apache.org/tomcat-80-eol.html)

### PR DESCRIPTION
**Pull request by julienchastang**
closes #41. FYI `server.xml` is for information purposes only. It is not added to the container, but rather falls out of it.

### CODE REVIEW

**Comment by julienchastang** [comment]
@kwilcox Notwithstanding concerns you [had in the past](https://github.com/Unidata/tomcat-docker/pull/37#issue-261377596), do you have any objections on the PR ending up in `master` and starting an `8.5` branch for this repo? Eventually thredds-docker will make use of it probably with the next release of the TDS. FYI [Tomcat 8.0 will be EOLed this year](https://tomcat.apache.org/tomcat-80-eol.html).

**Comment by kwilcox** [comment]
Are you proposing a `8.5.x` branch that will eventually be merged into `master`? Yes, that would be great and allow me to test out the changes as long as Docker Hub is setup to create images from branches. When it is merged into `master` we should maintain an `8.0.x` branch for those who need time to transition to `8.5.x`.

**Comment by julienchastang** [comment]
I just realized there is ambiguity here b/c, currently there's only and `8` branch. There is no `8.0` branch.

I guess I was thinking about this the other way around where this PR would end up in `master` (= `latest`) and `8.5` would be branched off of that. We'd also need to create an 8.0 branch based off of current `master`. If needing `8.0`, then use that branch. `8.0` would continue to be supported for some time, though I don't really anticipate needing a lot of upkeep on `8.0`.

Not sure what to do with current `8` branch. Maybe deprecate it since it is confusing, but also equate it with `8.0` for the time being. So in summary, I am proposing:

1. Create an `8.0` branch that will be maintained for some time.
2. Merge this PR into `master`. That's `latest`.
3. Create `8.5` from new `master`.
4. Gently deprecate `8` though effectively equate with 8.0 for the time being.

Ohh and yes, DockerHub will be setup with auto-builds for all relevant branches.

**Comment by kwilcox** [comment]
That all sounds good!

**Comment by kwilcox** [comment]
@julienchastang did you test this at all? I can not get the 8.5 image to run correctly.

```
$ docker pull unidata/tomcat-docker:8.5
8.5: Pulling from unidata/tomcat-docker
Digest: sha256:e626ca90315302a12ca7ae19656245ba10cd78a13066d673354b0c0410f0b0f1
Status: Image is up to date for unidata/tomcat-docker:8.5

$ docker run --rm -p 8080:8080 --name tc1 unidata/tomcat-docker:8.5
error: exec: "start-tomcat.sh": executable file not found in $PATH
```

```
$ docker pull unidata/tomcat-docker:8
8: Pulling from unidata/tomcat-docker
Digest: sha256:1f287a991c80ee40fd6349e75f3138a6f631e56a0356581485649987125c6b58
Status: Image is up to date for unidata/tomcat-docker:8

$ docker run --rm -p 8080:8080 --name tc1 unidata/tomcat-docker:8
+ trap 'echo TRAPed signal' HUP INT QUIT KILL TERM
+ startup.sh -security
Tomcat started.
+ true
+ sleep 10000
```

**Comment by kwilcox** [comment]
The travis tests are not working as intended:

```
0.02s$ curl -o /dev/null http://127.0.0.1:8080/sample/index.html || true
curl: (56) Recv failure: Connection reset by peer
```

But they still passed. Obviously the `|| true` is going to pass that test no matter if the container was actually running tomcat or failed to start tomcat!

**Comment by julienchastang** [comment]
Yes. I definitely tested this beyond travis and had the impression things were working. I'll investigate what is wrong here. I think the `curl || true` command you are referring to is to fire up tomcat with an http hit with additional testing beyond that. I'll look into that too.

**Comment by julienchastang** [comment]
Kyle, I did a few brief checks and I'll continue digging into this tomorrow, but I think there is something stale on your end somewhere. I'd make sure your Docker environment and unidata/tomcat images are up-to-date.

**Pull request merged**
